### ISSUE TITLE
What information does the muct76.model of the muct data set contain?

### ISSUE THREAD

**Issue by sophia071294** [StephenMilborrow/muct#1]
What information does the muct76.model of the muct data set contain?
3
76
751
41
0.1
0.1
1.2
1.45
1
0.65
0
0.25
41
152
-0.00383798
-0.0366214
-0.0831502
-0.161586
-0.189107
-0.135348
-0.0501795
0.0032351
0.072109
0.18873
0.289635
0.290203
0.232104
0.173315
0.1578
0.0467987
0.0395346
0.0152529
-0.000969985
....

They  are in the muct76.model file. What do these numbers represent?﻿

 Please help me! I wait for your answer.

**Comment by StephenMilborrow** [comment]
There is no file "model76.model" in this repository.  You must have got that file from somewhere else.
