### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by richipower** [StephenMilborrow/muct#4]
Hello, i would like to know the license of the dataset? is it possible to use derived data from the dataset in commercial purposes?

**Comment by StephenMilborrow** [comment]
Yes you can use the MUCT data to build applications that will be used commercially.   Just respect the privacy of the individuals by not reproducing the images (except for the images that are specifically allowed to be reproduced).
Steve

From: richipower 
Sent: Friday, January 25, 2019 6:30 AM
To: StephenMilborrow/muct 
Cc: Subscribed 
Subject: [StephenMilborrow/muct] License? (#4)

Hello, i would like to know the license of the dataset? is it possible to use derived data from the dataset in commercial purposes?

**Comment by richipower** [comment]
thank you for your answer
