### ISSUE TITLE
Camera calibration images

### ISSUE THREAD

**Issue by simonfojtu** [StephenMilborrow/muct#5]
Hi, could you please upload the images for camera calibration?

**Comment by StephenMilborrow** [comment]
I put the reference images at

http://www.milbo.org/muct/muct-calib00.tar.gz

There are five images per set, for the five cameras, see the MUCT paper.   I have a whole bunch of such images.  They are all about the same, I chose just some of them to upload, but let me know if you want more.

If they are of any use, let me know.   Sometime I’ll put them up on the MUCT github page.

Regards,
Steve

From: Šimon Fojtů 
Sent: Thursday, February 14, 2019 1:05 AM
To: StephenMilborrow/muct 
Cc: Subscribed 
Subject: [StephenMilborrow/muct] Camera calibration images (#5)

Hi, could you please upload the images for camera calibration?

**Comment by simonfojtu** [comment]
Thank you
